// ../../../Utils/constants.js

export const countries = [
    // 🌍 Africa
    'Nigeria',
    'South Africa',
    'Kenya',
    'Egypt',
    'Ethiopia',
    'Morocco',
    'Ghana',
    'Algeria',
    'Uganda',
    'Tanzania',
    'Rwanda',
    'Ivory Coast',
    'Tunisia',
    'Sudan',
    'Cameroon',

    // 🌏 Asia
    'China',
    'India',
    'Japan',
    'South Korea',
    'Indonesia',
    'Thailand',
    'Philippines',
    'Vietnam',
    'Malaysia',
    'Pakistan',
    'Bangladesh',
    'Saudi Arabia',
    'United Arab Emirates',
    'Iran',
    'Singapore',

    // 🌍 Europe
    'United Kingdom',
    'Germany',
    'France',
    'Italy',
    'Spain',
    'Netherlands',
    'Sweden',
    'Norway',
    'Switzerland',
    'Portugal',
    'Poland',
    'Greece',
    'Belgium',
    'Denmark',
    'Ireland',

    // 🌎 North America
    'United States',
    'Canada',
    'Mexico',
    'Guatemala',
    'Cuba',
    'Dominican Republic',
    'Panama',
    'Honduras',
    'Costa Rica',
    'Jamaica',
    'Haiti',
    'Nicaragua',
    'El Salvador',
    'Trinidad and Tobago',
    'Bahamas',

    // 🌎 South America
    'Brazil',
    'Argentina',
    'Colombia',
    'Chile',
    'Peru',
    'Venezuela',
    'Ecuador',
    'Uruguay',
    'Paraguay',
    'Bolivia',
    'Guyana',
    'Suriname',
    'French Guiana',
    'Falkland Islands',
    'Panama', // also part of Central America

    // 🌏 Oceania
    'Australia',
    'New Zealand',
    'Fiji',
    'Papua New Guinea',
    'Samoa',
    'Tonga',
    'Vanuatu',
    'Solomon Islands',
    'Micronesia',
    'Palau',
    'Kiribati',
    'Marshall Islands',
    'Tuvalu',
    'Nauru',
    'Cook Islands',
];

export const allLanguages = [
    'English',
    'Spanish',
    'French',
    'German',
    'Chinese',
    'Japanese',
    'Portuguese',
    'Hindi',
    'Arabic',
    'Russian',
    // Add more languages as needed
];